#! /usr/bin/python3.5

print ("How old are you?", end=' ')
age = input()
print("How tall are you?")
height = input()
print("How much do you weigh?")
weight = input()

print ("What is your {} " .format(age))
