#! /usr/bin/python3


age = input("How old are you")
height = input("What is your height?")
weight = input("What is your weight?")

print("So you're %s, height %s and weight %s" % (age, height, weight))
